version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.1.0

jobs:
  main:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - aws-ecr/build-and-push-image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          region: ${AWS_DEFAULT_REGION}
          repo: dbt-serverless
          tag: ${CIRCLE_SHA1}


workflows:
  version: 2
  flow:
    jobs:
      - main
